# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccd24ddf60ba2e93ba554be4b749c240c89c426e25fa1e3ad39c61e16ef8e785a077fb669fabb7f7a4c657ab9bf2502e58445dcf1f9812600488e6c07737f660

test:
  secret_key_base: a0ea1502b81c02836e66f06993f198e72a24b77de8b7690161719b9a2fc38cae3ae403f6abe9d7e027027c9b6136ecbb13d0b004ca789ce306e12f5d6b544427

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
